---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse-client distrib
      become: true
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-client-21.1.9.41-2.noarch.rpm"
        dest: "/home/yc-user/clickhouse-client-21.1.9.41-2.noarch.rpm"

    - name: Get clickhouse-server distrib
      become: true
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-server-21.1.9.41-2.noarch.rpm"
        dest: "/home/yc-user/clickhouse-server-21.1.9.41-2.noarch.rpm"

    - name: Get clickhouse-common-static distrib
      become: true
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-21.1.9.41-2.x86_64.rpm"
        dest: "/home/yc-user/clickhouse-common-static-21.1.9.41-2.x86_64.rpm"

    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - "/home/yc-user/clickhouse-client-21.1.9.41-2.noarch.rpm"
          - "/home/yc-user/clickhouse-server-21.1.9.41-2.noarch.rpm"
          - "/home/yc-user/clickhouse-common-static-21.1.9.41-2.x86_64.rpm"
      notify: Start clickhouse service

    - name: Flush handlers
      meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
